version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6
        environment:
          NPM_CONFIG_COLOR: false
          NPM_CONFIG_LOGLEVEL: warn
          NPM_CONFIG_PROGRESS: false
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - cabal-cache-{{ checksum ".circleci/config.yml" }}
      - run: sudo apt-get install cabal-install
      - run: cabal update
      - run: cabal sandbox init
      - run: cabal install shellcheck-0.4.7
      - save_cache:
          key: cabal-cache-{{ checksum ".circleci/config.yml" }}
          paths:
            - .cabal-sandbox
      - run: npm install
      - run: PATH="$(pwd)/.cabal-sandbox/bin:$PATH" npm test
